accelerate launch train_dreambooth_boft.py \
  --pretrained_model_name_or_path="autodl-tmp" \
  --instance_data_dir="GG_band_processed" \
  --output_dir="outputs/ggbond_oft" \
  --instance_prompt="a photo of sks GG Bond pig, 2d cartoon, dressed in a red jumpsuit, red headgear with yellow glasses,  iconic pig snout, yellow snout pattern on chest, pure white background" \
  --validation_prompt="a photo of sks GG Bond pig, 2d cartoon, dressed in a red jumpsuit, red headgear with yellow glasses,  iconic pig snout, yellow snout pattern on chest, pure white background" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=2e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=1000 \
  --checkpointing_steps=200 \
  --validation_steps=200 \
  --use_8bit_adam \
  --use_boft \
  --boft_bias="none" \
  --boft_n_butterfly_factor=1 \
  --report_to="tensorboard" \
  --wandb_project_name="ggbond_oft_project" \
  --wandb_run_name="ggbond_v1_run" \
  --seed="42" \
  --mixed_precision="no"
